### ISSUE TITLE
Add Nodle Arcadia to Polkascan.io

### ISSUE THREAD

**Issue by emielvanderhoek** [NodleCode/chain#27]
Issue to keep tracks of coordination regarding Polkascan support for Nodle (Arcadia) Network.

Nodle Arcia on Polkascan.io: https://polkascan.io/pre/nodle-arcadia

**Comment by emielvanderhoek** [comment]
Finalization is stalling at block 140798.
This may be an issue with grandpa finality or changes to the validator set.

![image](https://user-images.githubusercontent.com/14069142/78760183-0f244a00-7981-11ea-9c70-ce5fe52b1aaf.png)

**Comment by emielvanderhoek** [comment]
Polkascan will continue harvesting beyond block 140798 when finalization is resumed.
This issue required follow-up: https://github.com/NodleCode/chain/issues/28

**Comment by ETeissonniere** [comment]
#28 is now closed due to some network upgrades! I guess the last step is to reset your databases so that the UI shows the current network?

**Comment by emielvanderhoek** [comment]
We are crunching through some of the substrate alpha.5 and alpha.6 changes. That should be done soon. Then we’ll reset Nodle Arcadia on Polkascan.io.

**Comment by emielvanderhoek** [comment]
We are crunching through some of the substrate alpha.5 and alpha.6 changes. That should be done soon. Then we’ll reset Nodle Arcadia on Polkascan.io.

**Comment by ETeissonniere** [comment]
Hi @emielvanderhoek just wanted to follow up on this and check if there is anything we can do to help?
