### ISSUE TITLE
Implement `try-runtime`

### ISSUE THREAD

**Issue by ETeissonniere** [NodleCode/chain#414]
Using the `try-runtime` feature of substrate would allow us to better test runtime migrations.
Let's make sure we support it and have a script in the `.maintain` folder to test this. Then we should make it part of the unit tests.

https://docs.substrate.io/v3/tools/try-runtime
https://docs.substrate.io/how-to-guides/v3/tools/try-runtime/

https://github.com/parallel-finance/parallel/blob/master/.github/workflows/try-runtime.yml

**Comment by noisefloors** [comment]
@ETeissonniere Was this resolved by @aliXsed's most recent PR? Minus the ops components, I believe so.

**Comment by ETeissonniere** [comment]
I believe so. Wanted to ask tonight

**Comment by aliXsed** [comment]
@noisefloors @ETeissonniere Everything in the description of this issue is addressed and a try-runtime test is part of our CI workflow. I haven't added a script in the .maintain folder though. Do we still need that? If yes, what should it do? Is it going to be similar to what we do in ci.yml?

**Comment by ETeissonniere** [comment]
We should be fine, will go ahead and close this
