### ISSUE TITLE
Improve building chain docker images

### ISSUE THREAD

**Issue by aliXsed** [NodleCode/chain#452]
1. Set our Docker upstream image to be ubuntu:focal (or using its release tag 20.04) instead of ubuntu. I suspect our current Dockerfile resolves the most current release (impish), which only has support through July, 2022 rather than April, 2025.

2. Relieve the disk space limits on the CI worker by only installing required toolchain dependencies in the Docker environment. The below diff contains both changes:

```
diff --git a/Dockerfile b/Dockerfile
index 7460bcfb28..cc626eedd7 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,4 +1,4 @@
-FROM ubuntu as builder
+FROM ubuntu:focal as builder
 
 ARG PROFILE=release
 WORKDIR /nodle-chain
@@ -8,14 +8,14 @@ COPY . /nodle-chain
 RUN apt-get update && \
        apt-get upgrade -y && \
        DEBIAN_FRONTEND=noninteractive apt-get install -y cmake pkg-config libssl-dev git clang build-essential curl
-RUN curl https://sh.rustup.rs -sSf | sh -s -- -y && \
+RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain none && \
        export PATH=$PATH:$HOME/.cargo/bin && \
        scripts/init.sh && \
        cargo build -p nodle-chain --$PROFILE
 
 # ===== SECOND STAGE ======
 
-FROM ubuntu
+FROM ubuntu:focal
 
 ARG PROFILE=release
```

3. Only build docker images for pushes to the master branch rather than any push to any branch. Make sure it wouldn't break any unit tests which would potentially depend on the intermediate docker images.

**Comment by ETeissonniere** [comment]
@aliXsed looks like using the minimal rust install triggers some [build issues](https://github.com/NodleCode/chain/runs/4848010789?check_suite_focus=true)

**Comment by noisefloors** [comment]
@ETeissonniere @aliXsed If I'm not mistaken, you'll want to [check `scripts/init.sh`](https://github.com/NodleCode/chain/blob/master/scripts/init.sh) and ensure we have the correct toolchain installed with matching system dependencies.
