### ISSUE TITLE
Indicate valid range for types used by polkadot.js/apps

### ISSUE THREAD

**Issue by aliXsed** [NodleCode/chain#525]
As suggested [here](https://github.com/paritytech/substrate/issues/10817#issuecomment-1050237296) and for ensuring reliable backwards processing of the blocks and events we need to indicate the valid range for our chain's custom types that we share with [polkadot apps](https://github.com/polkadot-js/apps/blob/master/packages/apps-config/src/api/spec/nodle.ts). This is important for historical data but going forward polkadot.js newer versions (>= V14) is able to extract the types from the chain's metadata (supported by our latest chain version).

**Comment by ETeissonniere** [comment]
@aliXsed now that types metadata are fetched from the node itself, do we even need to maintain some type mappings?

**Comment by aliXsed** [comment]
> @aliXsed now that types metadata are fetched from the node itself, do we even need to maintain some type mappings?

@ETeissonniere it could be useful for decoding old blocks of our solo chain but since we have stopped that chain, I'm going to close this ticket.
