### ISSUE TITLE
Upgrade chain based on polkadot v0.9.20

### ISSUE THREAD

**Issue by aliXsed** [NodleCode/chain#593]
Polkadot has released [0.9.20](https://github.com/paritytech/polkadot/releases/tag/v0.9.20) and Cumulus is now on (https://github.com/paritytech/cumulus/tree/polkadot-v0.9.20). We need to upgrade our parachain eden runtime and client to based on polkadot 0.9.20.

**Comment by ETeissonniere** [comment]
@aliXsed shall we close this issue? Looks like the PR fixing it is merged
