### ISSUE TITLE
Investigate Eden's high and fluctuating block time

### ISSUE THREAD

**Issue by aliXsed** [NodleCode/chain#608]
Eden, Nodle's main parachain, is now running the runtime version 10 based on Polkadot 0.9.20 but the block time pattern that we had been observing from early on remains almost the same. The block time is regularly fluctuating between 12s to 24s with some higher spikes (which are of less concern):

![Screen Shot 2022-06-17 at 10 20 41 AM](https://user-images.githubusercontent.com/6517909/174188310-0b9c1aa0-c213-454c-9014-4b48c82ca3c6.png)

[This](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fnodle-parachain.api.onfinality.io%2Fpublic-ws#/explorer/latency) is not happening to our [parachain test net](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fnode-6913072722034561024.lh.onfinality.io%2Fws%3Fapikey%3D84d77e2e-3793-4785-8908-5096cffea77a#/explorer/latency) on rococo despite both running the same runtime and client versions. 
Here is the [public telemetry](https://telemetry.polkadot.io/#list/0x97da7ede98d7bad4e36b4d734b6055425a3be036da2a332ea5a7037656427a21) for Eden. Out of the nodes you may on that dashboard, at least 5 of them are collators and forced to author. We have the same number of collators for our test net. One know difference between our test net and the main net is the transaction traffic which is about half or less on the test net.

**Comment by aliXsed** [comment]
We have tested upgrading our collator machines to more powerful VMs and the issue remained the same. We found out the block delay seems to be rather correlated to the block size. It's potentially possible if we further limit our block weights we can tame the fluctuations. Here is a screenshot of our intermittent big block cases: 
<img width="1703" alt="Screen Shot 2022-06-22 at 8 49 59 AM" src="https://user-images.githubusercontent.com/6517909/174919716-8024b21f-b51f-4828-959e-ee9645ecc084.png">

**Comment by simonsso** [comment]
The very regular pattern looks like there are some times when none of the colators are creating a block expecting someone else to do that. 

A quick check with the last 100 blocks show all blocks are created by either `4kaLZH5ASwCdVrR5pWp5JRWHLV5rL3FrRJdFo85Qsk8ybkqG` ,`4mZvXfESP9MeebPZJTxvUmXtxr7t6fsREzFhH5jnQsJNwg9g` or `4n4fXWiz5Vv9fTSGX1RXhJ7oesQkPaE8eyw4GXafYn7mhTR1

Do we have more colators which should produce a block from time to time or do the three existing block producer believe there is another one?

**Comment by aliXsed** [comment]
@simonsso This may be related to having approved collators which are not up any more. We definitely need to address this and check if this could lead to robust block production. I think one of you @ETeissonniere or @rajesh-nodle who did the key injections for Eden should be in a better place to fix this quickly.

**Comment by aliXsed** [comment]
@simonsso's finding was spot on. After re-inserting the session keys for bc2 and bc4 two of our collators, they started to take their turn and produce blocks which then regulated the chain's block production. Our previous suspicion where we noted the large block size and its potential correlation with the block time had later proved to not be the root cause, However it spurred us to make some beneficial optimisations for those large chunks of extrinsics which will save our chain's resources regardless.
