### ISSUE TITLE
Fix hardware benchmark command

### ISSUE THREAD

**Issue by aliXsed** [NodleCode/chain#656]
As discussed [here](https://substrate.stackexchange.com/questions/4085/how-to-see-the-hardware-benchmark-results) and [suggested](https://substrate.stackexchange.com/questions/4085/how-to-see-the-hardware-benchmark-results/4096#comment3897_4096) by @ggwpez, the command to benchmark the hardware needs to be debugged and fixed.

**Comment by ggwpez** [comment]
Could be this one https://github.com/paritytech/substrate/issues/11691

**Comment by rajesh-nodle** [comment]
With branch `polkadot-v0.9.27`, issue not seen, as commented by @ggwpez, PR for https://github.com/paritytech/substrate/issues/11691 already solved the issue ...

![](https://i.imgur.com/RIWrAdA.png)
