### ISSUE TITLE
Permissionless Emergency Shutdown

### ISSUE THREAD

**Issue by ETeissonniere** [NodleCode/chain#657]
# Forewords
This issue describes a new feature to be implemented as a new pallet for the Nodle Parachain. Following the recent hack of Acala's Parachain, we would like to create a few capabilities for Nodle:
- we want to be able to better monitor on-chain heuristics and detect anomalies
- would an issue arise, we want to quickly trigger a "maintenance" mode that would pause all non-critical features of the parachain
- a single entity shouldn't control this system due to the potential risk of abuses, and the added maintenance cost for this single party, instead, we can build it in a permissionless, decentralized way (a first in the ecosystem from what I know)
- permissionless does not mean stake-less, triggering such a maintenance mode should be rather expensive and force the caller to put a sizable amount of funds at risk, would they misbehave and activate a maintenance mode for nothing, they should lose such funds
- I do not believe we need an incentive system here, the incentive of not losing all your coins or portfolio value should be enough for anybody interested to trigger the maintenance mode

# Design

## Extrinsic

We would need one extrinsic to be in place, `trigger(origin, length)` which takes in some arguments:
- `origin`: basic for substrate, indicates who is calling the extrinsic
- `length`: number of blocks for which the maintenance mode should be maintained (the longer it is, the more expensive the call should be)

I would suggest adding a second extrinsic to allow governance control of this feature, `force_trigger(origin, length)` with a similar set of parameters, however, it should be `ensure_root` protected to ensure only the chain's governance can call it. This call would not need additional payment to trigger the maintenance mode.

Last but not least, `extend(origin, length)` should be usable to extend the maintenance window period, it should be callable during the maintenance mode.

`length` can be set to an arbitrarily high value if necessary, for instance, a year or two. It is expected that a runtime upgrade fixing any issues would cancel the maintenance mode as necessary.

## Configuration Parameters

- `base_cost`: base cost in NODL one need to pay for each `trigger` call. Suggested value: 1M NODL.
- `block_cost`: additional for each block in `length` which specifies how long we need to be under maintenance. Suggested value: 10 NODL.

As such, the cost of a single `trigger` call would be: `transaction fee + base_cost + length * block_cost`.

If we consider an average block time of 12 seconds, putting the chain in maintenance for one week would cost `1M + 50_400 * 10 = 1,502,000 NODL`. This cost would be locked ("captured") by the pallet, two potential flows would be expected:
- **if the maintenance was triggered for no reason**: the chain's governance shall not refund the NODL
- **if the maintenance was triggered correctly**: the NODL should be sent back to the caller by the chain's governance

## Implementation

We previously had a very simple `emergency-shutdown` pallet that was tightly coupled to our other pallets. We do not want to reproduce this design, due to its lack of scalability and added maintenance cost (you'd need to ensure all your pallet's extrinsic double-check the shutdown state...). Instead, we can use `frame-system`'s `BaseCallFilter` configuration argument, our pallet can implement the `Contains<Call>` trait in a simple way:
- if we are under maintenance mode, only allow critical calls
- if not, allow everything

### What is a critical call

> This should be part of the pallet's configuration parameters for easier maintenance and configuration.

- calls to `system`
- calls to `timestamp`
- anything consensus-related: `authorship`, `session`
- calls to the maintenance/emergency shutdown pallet itself -> the pallet could make sure of this without requiring the integrator to specify it manually
- any governance calls: right now these would be calls to the tech committee, tomorrow it could be calls to `democracy` etc...

### Testing

- Let's ensure we test a local parachain with and without emergency shutdown triggered to ensure our list of critical calls is enough (ie. ensure we continue producing blocks).
- Let's add an integrity test that ensures that our whitelist of "critical" calls includes at least one extra pallet/call which could be used for governance. This is to ensure we don't shoot ourselves in the feet by mistake. This could be implemented in a naive way by simply verifying which pallets are included in the whitelist (ie. if we only have system, timestamp, and consensus, the test should fail). -> we can use the `integrity_test` hook for this

**Comment by Decentralized-Rob** [comment]
Excellent idea... thank you for suggesting.

**Comment by spacesmutje** [comment]
I totally support this proposal. Although i would raise the minimum to 2.5m token to keep the barrier as high as possible for bad actors.
