### ISSUE TITLE
polkadot-launch deprecated

### ISSUE THREAD

**Issue by ganesh1233456** [NodleCode/chain#721]
since `polkadot-launch` has been [deprecated](https://github.com/paritytech/polkadot-launch#%EF%B8%8F-deprecated-%EF%B8%8F). Will `cargo build --release -p nodle-parachain && polkadot-launch launch.json` still work?

**Comment by ETeissonniere** [comment]
Great question, for now it should. But we might have to provide alternative instructions in the future. cc @aliXsed

**Comment by aliXsed** [comment]
> Great question, for now it should. But we might have to provide alternative instructions in the future. cc @aliXsed

@ETeissonniere @ganesh1233456 it's still working and still better than its substitute `parachain-launch`. However since I have my own configuration, I haven't recently tried launch.json. @ganesh1233456 if you had any issues, let us know and we'll work it out.
The parachain-launch on the other side uses docker images instead of native binaries, but it may not work as smooth specially for a mac M1 machine. I had to tweak a couple of the things to get it working.

**Comment by ganesh1233456** [comment]
hey forgive me for the trouble! I am have having an issue on configuring polkadot-launch, even though I shouldn't ask this question here but `polkadot-launch` is deprecated, so I ask here. I installed  polkadot-launch with  `yarn global add polkadot-launch` and it installed successfully, On moving further steps, installing polkadot binary file, build successfully, but `cp ./target/release/polkadot ../polkadot-launch/bin/polkadot-relaychain` this step fails because,

```
ganesholi@Ganeshs-MacBook-Air polkadot % cp ./target/release/polkadot ../polkadot-launch/bin/polkadot-relaychain

cp: ../polkadot-launch/bin/polkadot-relaychain: Not a directory
ganesholi@Ganeshs-MacBook-Air polkadot % 
```

and I check, it's not directory it's file which installed while installing polkadot-launch. My question is should I clone `polkadot-launch` as well in the same dir as polkadot is? But [here](https://github.com/paritytech/polkadot-launch#install) no suggestion to do that. What's wrong I am doing on configuration? Can you give some advice?

**Comment by ETeissonniere** [comment]
@ganesh1233456 the error is related to how you are copying the `polkadot` binary. It isn't necessarily an issue with `polkadot-launch`. You might want to check whether the directory `../polkadot-launch/bin` exists. For the `launch.json` shipped within this repo, we expect to find the `polkadot` binary at this path: `/usr/local/bin/polkadot`.

Note that we ship a [devcontainer](https://github.com/NodleCode/chain/tree/master/.devcontainer) you could make use off that will come with everything pre-installed and ready to use. This includes `polkadot` and `polkadot-launch` themselves.

**Comment by simonsso** [comment]
@ganesh1233456 I have verified polkadot-launch to be running on the latest version. It may be deprecated but it still works.

**Comment by ganesh1233456** [comment]
thanks
