### ISSUE TITLE
Docker exiting [Relaychain] error=Subsystem(Generated(Context("Signal channel is terminated and empty.")))

### ISSUE THREAD

**Issue by Binotje** [NodleCode/chain#795]
I'm trying to setup a Collector Node but running into the same issue after a certain time. Im trying the docker setup and following the guide https://docs.nodle.com/docs/nodle-chain/become-a-collator.

The command i use on Docker version 24.0.6, build ed223bc:  docker run -p 9944:9944 -it nodlecode/chain:2.0.29 --chain eden --collator   --force-authoring --rpc-cors all --ws-port=9944   --name my-collator-1   --   --ws-port 9955 --name=my-relay-1 --chain=polkadot 

Log file in the attachment, it continues for a while ith the message [2m2023-10-22 23:58:14[0m [Relaychain] error=Subsystem(Generated(Context("Signal channel is terminated and empty.")))

Any idea what im doing wrong or how i can fix this?

[dockerlog.txt](https://github.com/NodleCode/chain/files/13127662/dockerlog.txt)

**Comment by aliXsed** [comment]
@Binotje please use the version 2.2.3
`docker run -p 9944:9944 -it nodlecode/chain:2.2.3 --chain eden --collator --force-authoring --rpc-cors all --ws-port=9944 --name my-collator-1 -- --ws-port 9955 --name=my-relay-1 --chain=polkadot`

**Comment by Binotje** [comment]
Thanks. That di the job.
